name: "Bug Report"
description: "Report and request a bug fix"
title: "[Bug] "
labels: ["type:bug", "status:todo"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Bug Summary"
      description: "Describe in one sentence"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction Steps"
      placeholder: |
        1. Go to …
        2. Click …
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - "p0 - Critical (service down)"
        - "p1 - High (major feature broken)"
        - "p2 - Medium (workaround exists)"
        - "p3 - Low (cosmetic)"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      placeholder: |
        - OS: 
        - Browser/Runtime: 
        - Version: 
