name: "Epic"
description: "Large feature bundle — composed of multiple Features/Stories (weeks to months)"
title: "[Epic] "
labels: ["type:epic", "status:todo"]
body:
  - type: textarea
    id: goal
    attributes:
      label: "Business Goal"
      description: "The problem or opportunity this Epic addresses. What business value does it create?"
      placeholder: "Due to problem X, Y is occurring. By solving this, we expect Z outcome."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Scope"
      description: "What is included / excluded"
      placeholder: |
        **In scope:**
        - 

        **Out of scope:**
        - 
    validations:
      required: true

  - type: textarea
    id: kpi
    attributes:
      label: "KPI / Success Metrics"
      placeholder: |
        - Metric 1: current X → target Y
        - Metric 2: …

  - type: textarea
    id: features
    attributes:
      label: "Sub-Features"
      description: "List of child Feature issues"
      placeholder: |
        - [ ] #issue — Feature name
        - [ ] #issue — Feature name

  - type: textarea
    id: done
    attributes:
      label: "Definition of Done"
      placeholder: |
        - [ ] All sub-Features closed
        - [ ] KPIs verified
        - [ ] Docs updated
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options: ["p0 - Critical", "p1 - High", "p2 - Medium", "p3 - Low"]
    validations:
      required: true
