name: "Feature / PRD"
description: "Single feature unit — child of an Epic, doubles as PRD (1–3 sprints)"
title: "[Feature] "
labels: ["type:feature", "status:todo"]
body:
  - type: textarea
    id: problem
    attributes:
      label: "Problem Definition"
      placeholder: "Users currently cannot do X, causing problem Y."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      placeholder: "We will build Z to solve this."
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: "Requirements"
      description: "Functional requirements table"
      placeholder: |
        | ID | Requirement | Priority |
        |----|-------------|----------|
        | F-1 | | p1 |
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria (Given-When-Then)"
      placeholder: |
        - Given [precondition], When [action], Then [expected result]
    validations:
      required: true

  - type: textarea
    id: epic
    attributes:
      label: "Parent Epic"
      placeholder: "Refs #issue"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options: ["p0 - Critical", "p1 - High", "p2 - Medium", "p3 - Low"]
    validations:
      required: true
