name: "User Story"
description: "User-perspective requirement unit (within 1 sprint)"
title: "[Story] As a "
labels: ["type:story", "status:todo"]
body:
  - type: textarea
    id: user_story
    attributes:
      label: "User Story"
      placeholder: "As a [user type], I want [to do something] so that [I achieve some goal]."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria (Given-When-Then)"
      placeholder: |
        - Given [precondition], When [action], Then [expected result]
    validations:
      required: true

  - type: dropdown
    id: points
    attributes:
      label: "Story Points"
      options: ["1", "2", "3", "5", "8", "13"]

  - type: textarea
    id: feature
    attributes:
      label: "Parent Feature"
      placeholder: "Refs #issue"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options: ["p0 - Critical", "p1 - High", "p2 - Medium", "p3 - Low"]
    validations:
      required: true
