name: "Task"
description: "Concrete technical work unit (1–3 days)"
title: "[Task] "
labels: ["type:task", "status:todo"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Task Description"
      description: "What needs to be implemented and how"
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "Completion Checklist"
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
        - [ ] Tests passing
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: "Work Area"
      options:
        - backend
        - frontend
        - infra
        - database
        - api
        - ai-agent
        - security
        - ux
        - docs
        - aipm
    validations:
      required: true

  - type: textarea
    id: parent
    attributes:
      label: "Parent Story / Feature"
      placeholder: "Refs #issue"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options: ["p0 - Critical", "p1 - High", "p2 - Medium", "p3 - Low"]
    validations:
      required: true
